# Generated by Django 5.2.6 on 2025-09-27 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('role', models.CharField(choices=[('ADMIN', 'Администратор'), ('CLIENT', 'Заказчик'), ('FOREMAN', 'Прораб'), ('INSPECTOR', 'Инспектор')], db_index=True, max_length=20)),
                ('token', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('ACCEPTED', 'Принято'), ('EXPIRED', 'Истекло'), ('REVOKED', 'Отозвано')], db_index=True, default='PENDING', max_length=20)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='objects.constructionobject')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='orgs.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
