# Generated by Django 5.2.6 on 2025-09-27 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('objects', '0001_initial'),
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unit', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('parsed', models.JSONField(default=dict)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to='documents.attachment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QualityPassport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.attachment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TTNDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.attachment')),
                ('ocr', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.ocrresult')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('delivered_at', models.DateTimeField(db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deliveries', to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='objects.constructionobject')),
                ('photos', models.ManyToManyField(blank=True, to='documents.attachment')),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='schedules.workitem')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.materialtype')),
                ('quality_passport', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.qualitypassport')),
                ('ttn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.ttndocument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
