# Generated by Django 5.2.6 on 2025-09-27 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('objects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('issuer_type', models.CharField(choices=[('CUSTOMER', 'Заказчик'), ('INSPECTOR', 'Инспектор')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Открыто'), ('IN_PROGRESS', 'В работе'), ('RESOLVED', 'Решено'), ('ACCEPTED', 'Принято'), ('REJECTED', 'Отклонено')], db_index=True, default='OPEN', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Низкая'), ('MEDIUM', 'Средняя'), ('HIGH', 'Высокая'), ('CRITICAL', 'Критическая')], db_index=True, default='MEDIUM', max_length=20)),
                ('sla_due', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at_client_time', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='issues.issuecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.constructionobject')),
                ('photos', models.ManyToManyField(blank=True, related_name='%(class)s_photos', to='documents.attachment')),
            ],
            options={
                'verbose_name': 'Замечание заказчика',
                'verbose_name_plural': 'Замечания заказчика',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Открыто'), ('IN_PROGRESS', 'В работе'), ('RESOLVED', 'Решено'), ('ACCEPTED', 'Принято'), ('REJECTED', 'Отклонено')], db_index=True, default='OPEN', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Низкая'), ('MEDIUM', 'Средняя'), ('HIGH', 'Высокая'), ('CRITICAL', 'Критическая')], db_index=True, default='MEDIUM', max_length=20)),
                ('sla_due', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at_client_time', models.DateTimeField(blank=True, null=True)),
                ('normative_link', models.CharField(blank=True, max_length=512, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='issues.issuecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.constructionobject')),
                ('photos', models.ManyToManyField(blank=True, related_name='%(class)s_photos', to='documents.attachment')),
            ],
            options={
                'verbose_name': 'Нарушение инспектора',
                'verbose_name_plural': 'Нарушения инспектора',
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(db_index=True, default=False)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_resolutions', to=settings.AUTH_USER_MODEL)),
                ('attachments', models.ManyToManyField(blank=True, to='documents.attachment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolutions', to=settings.AUTH_USER_MODEL)),
                ('remark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='issues.remark')),
                ('violation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='issues.violation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
