# Generated by Django 5.2.6 on 2025-09-27 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('polygon', models.JSONField()),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PENDING_ACTIVATION', 'Ожидает активации'), ('ACTIVE', 'Активен'), ('COMPLETED', 'Завершен')], db_index=True, default='DRAFT', max_length=20)),
                ('plan_start', models.DateField(blank=True, db_index=True, null=True)),
                ('plan_end', models.DateField(blank=True, db_index=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='orgs.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningAct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.attachment')),
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opening_act', to='objects.constructionobject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_acts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SUBMITTED', 'Отправлено'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено')], db_index=True, default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, null=True)),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_checklists', to=settings.AUTH_USER_MODEL)),
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opening_checklist', to='objects.constructionobject')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_checklists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Администратор'), ('CLIENT', 'Заказчик'), ('FOREMAN', 'Прораб'), ('INSPECTOR', 'Инспектор')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='objects.constructionobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('object', 'user', 'role')},
            },
        ),
    ]
